# Generated by Django 5.1.4 on 2026-07-24 22:52

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ملک')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.BigIntegerField(verbose_name='قیمت (تومان)')),
                ('transaction_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره')], max_length=10, verbose_name='نوع معامله')),
                ('area', models.PositiveIntegerField(verbose_name='متراژ (متر مربع)')),
                ('rooms', models.PositiveSmallIntegerField(verbose_name='تعداد اتاق')),
                ('floor', models.PositiveSmallIntegerField(default=0, verbose_name='طبقه')),
                ('total_floors', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد کل طبقات')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال ساخت')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='آسانسور')),
                ('has_parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('has_warehouse', models.BooleanField(default=False, verbose_name='انباری')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='بالکن')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='طول جغرافیایی')),
                ('image', models.ImageField(upload_to='properties/', validators=[apps.core.validators.validate_image_file], verbose_name='تصویر اصلی')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='properties/', validators=[apps.core.validators.validate_image_file], verbose_name='تصویر دوم')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='properties/', validators=[apps.core.validators.validate_image_file], verbose_name='تصویر سوم')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='properties/', validators=[apps.core.validators.validate_image_file], verbose_name='تصویر چهارم')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='team.teammember', verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property', verbose_name='ملک')),
            ],
            options={
                'verbose_name': 'علاقه\u200cمندی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValuationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی مالک')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('transaction_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره')], max_length=10, verbose_name='نوع درخواست')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس ملک')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ (متر مربع)')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد اتاق')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات مالک درباره ملک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='valuation_requests/', validators=[apps.core.validators.validate_image_file], verbose_name='تصویر اول')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='valuation_requests/', validators=[apps.core.validators.validate_image_file], verbose_name='تصویر دوم')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='valuation_requests/', validators=[apps.core.validators.validate_image_file], verbose_name='تصویر سوم')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewed', 'بررسی شد'), ('contacted', 'تماس گرفته شد'), ('rejected', 'رد شد')], default='pending', max_length=15, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت داخلی (برای مشاوران)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('assigned_advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_requests', to='team.teammember', verbose_name='مشاور مسئول پیگیری')),
            ],
            options={
                'verbose_name': 'درخواست ارزیابی ملک',
                'verbose_name_plural': 'درخواست\u200cهای ارزیابی ملک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='properties.property', verbose_name='ملک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_properties', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید ملک',
                'verbose_name_plural': 'تاریخچه بازدید ملک\u200cها',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', 'transaction_type'], name='properties__is_publ_49d2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='properties__created_9ef325_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-views_count'], name='properties__views_c_0b3478_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'property')},
        ),
        migrations.AlterUniqueTogether(
            name='propertyview',
            unique_together={('user', 'property')},
        ),
    ]
