# Generated by Django 5.1.4 on 2026-07-24 22:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='شماره تماس معتبر وارد کنید (مثال: 09121234567).', regex='^0?9\\d{9}$|^0\\d{10}$')], verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('message', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='properties.property', verbose_name='ملک مرتبط')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر (در صورت ورود به حساب)')),
            ],
            options={
                'verbose_name': 'درخواست تماس',
                'verbose_name_plural': 'درخواست\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
    ]
