# Generated by Django 5.1.4 on 2026-07-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('buying', 'خرید'), ('renting', 'اجاره'), ('legal', 'حقوقی'), ('ai', 'تحلیل هوشمند')], default='general', max_length=20, verbose_name='دسته\u200cبندی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
            ],
            options={
                'verbose_name': 'پرسش متداول',
                'verbose_name_plural': 'پرسش\u200cهای متداول',
                'ordering': ['category', 'order'],
            },
        ),
    ]
