# Generated by Django 5.1.4 on 2026-07-24 22:52

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(verbose_name='متن مقاله')),
                ('summary', models.CharField(max_length=300, verbose_name='خلاصه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', validators=[apps.core.validators.validate_image_file], verbose_name='تصویر شاخص')),
                ('tags', models.CharField(blank=True, max_length=250, verbose_name='برچسب\u200cها (با ویرگول جدا کنید)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
