# Generated by Django 5.1.4 on 2026-07-25 19:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('consultation', 'کارشناسی'), ('visit', 'بازدید'), ('service', 'سرویس'), ('call', 'تماس'), ('meeting', 'جلسه')], max_length=20, verbose_name='نوع فعالیت')),
                ('customer_name', models.CharField(blank=True, max_length=150, verbose_name='نام مشتری')),
                ('customer_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='شماره تماس معتبر وارد کنید (مثال: 09121234567).', regex='^0?9\\d{9}$|^0\\d{10}$')], verbose_name='شماره تماس مشتری')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان برنامه\u200cریزی\u200cشده')),
                ('is_done', models.BooleanField(default=False, verbose_name='انجام\u200cشده')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='یادآوری ارسال\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='team.teammember', verbose_name='مشاور')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='properties.property', verbose_name='ملک مرتبط')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ فعالیت\u200cها',
                'ordering': ['-scheduled_at', '-created_at'],
                'indexes': [models.Index(fields=['advisor', '-created_at'], name='crm_activit_advisor_32cf7c_idx'), models.Index(fields=['reminder_sent', 'scheduled_at'], name='crm_activit_reminde_0353d1_idx')],
            },
        ),
    ]
