# Generated by Django 5.1.4 on 2026-07-25 20:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_task'),
        ('properties', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تماس معتبر وارد کنید (مثال: 09121234567).', regex='^0?9\\d{9}$|^0\\d{10}$')], verbose_name='شماره تماس')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='نام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='اولین تماس')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('stage', models.CharField(choices=[('new', 'لید جدید'), ('contacted', 'تماس گرفته شد'), ('viewing', 'بازدید'), ('negotiation', 'مذاکره'), ('contract', 'قرارداد'), ('won', 'موفق'), ('lost', 'ناموفق')], default='new', max_length=20, verbose_name='مرحله')),
                ('value', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ارزش تخمینی معامله (تومان)')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='team.teammember', verbose_name='مشاور مسئول')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.customer', verbose_name='مشتری')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='properties.property', verbose_name='ملک مرتبط')),
            ],
            options={
                'verbose_name': 'فرصت فروش',
                'verbose_name_plural': 'قیف فروش',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['advisor', 'stage'], name='crm_deal_advisor_f578e2_idx')],
            },
        ),
    ]
