# Generated by Django 5.1.4 on 2026-07-26 07:32

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_task_completed_at'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'خیلی ضعیف'), (2, 'ضعیف'), (3, 'متوسط'), (4, 'خوب'), (5, 'عالی')], verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, verbose_name='نظر مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='crm.deal', verbose_name='فرصت فروش')),
            ],
            options={
                'verbose_name': 'نظرسنجی رضایت',
                'verbose_name_plural': 'نظرسنجی\u200cهای رضایت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'قرارداد'), ('power_of_attorney', 'وکالت\u200cنامه'), ('ownership_deed', 'سند مالکیت'), ('id_card', 'مدرک شناسایی'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع سند')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', validators=[apps.core.validators.validate_document_file], verbose_name='فایل')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('expiry_reminder_sent', models.BooleanField(default=False, verbose_name='یادآوری انقضا ارسال\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.customer', verbose_name='مشتری')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.deal', verbose_name='فرصت فروش مرتبط')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='team.teammember', verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expiry_reminder_sent', 'expiry_date'], name='crm_documen_expiry__75f253_idx')],
            },
        ),
    ]
