# Generated by Django 5.1.4 on 2026-07-24 22:52

import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('role', models.CharField(choices=[('manager', 'مدیر مجموعه'), ('investment', 'مشاور سرمایه\u200cگذاری'), ('rent', 'مشاور اجاره'), ('sale', 'مشاور فروش'), ('legal', 'مشاور حقوقی')], default='sale', max_length=20, verbose_name='سمت')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', validators=[apps.core.validators.validate_image_file], verbose_name='تصویر')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.OneToOneField(blank=True, help_text='در صورت اتصال، این مشاور می\u200cتواند وارد پنل مدیریت مشاوران شود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری مرتبط')),
            ],
            options={
                'verbose_name': 'مشاور',
                'verbose_name_plural': 'مشاوران',
                'ordering': ['order', 'name'],
            },
        ),
    ]
